manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: 6de70d4d01de26be6d7e27bccda0875f8381e7e8
      import: true

  self:
    path: zephcore
